# Generated by Django 5.1.2 on 2024-10-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tabom", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="like",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
